### ISSUE TITLE
IMU: Set up, learn, and make accessible.

### ISSUE THREAD

**Issue by pdxaeroman** [LaSalleRobots/PowerPlay#20]
May be a stepping stone for #4 , #6 , #11

**Comment by lukasmwerner** [comment]
We just need to get the 180 hemispheres working in a 360. 

then we can close this

**Comment by lukasmwerner** [comment]
Just ordered a BN055 breakout board so we can get that nice Z axis data

**Comment by pdxaeroman** [comment]
the 180 hemispheres are literally the same thing. There is no difference, in data, or usability... it's just translated 180 degrees

**Comment by lukasmwerner** [comment]
so sadly the datasheet definition of -180 to +180 is very different to the mathematical expression. :( 

The definition translated is that it means mathematically -90 to +90 from its initial orientation. But we need to keep track if it goes past that -90 or +90 to know which quadrant it is in.

**Comment by pdxaeroman** [comment]
oh

**Comment by pdxaeroman** [comment]
How is this imu configuration even useful enough to build it into the control hub? Lol

**Comment by lukasmwerner** [comment]
Ummmmm idk its expected to just lay it flat on the ground and then read that data lol (and if you dont... then you better understand how the sensor really works)

**Comment by pdxaeroman** [comment]
How many things would we screw up if we mounted it flat?

**Comment by pdxaeroman** [comment]
you just bought a gyro so I guess it's kind of moot, but hypothetically

**Comment by lukasmwerner** [comment]
Yeah ummmm idk they are kinda big. but if we stacked them maybe? 🤷  (i think that would kinda sick) idk where it would fit tho lol

**Comment by pdxaeroman** [comment]
Would only need to do this to the control hub, expansion could remain on the drive wall. We talkin mega jank here

**Comment by lukasmwerner** [comment]
Yeah agreed. Anyways here is the sensor i just purchased: 
<img width="349" alt="Screen Shot 2022-11-30 at 2 37 59 PM" src="https://user-images.githubusercontent.com/55150634/204923322-062d960b-95a0-42e9-9204-ea9d7663fca5.png">
<img width="573" alt="Screen Shot 2022-11-30 at 2 38 15 PM" src="https://user-images.githubusercontent.com/55150634/204923385-121e211f-ba32-4a13-85e4-6a19edafbc57.png">


It is the same sensor just on a small carrier board. Im certain that this sensor is significantly easier for us to use since im guessing we dont want to build kalman filters to then integrate the different sensor info together.

**Comment by lukasmwerner** [comment]
WE DID IT!

**Comment by pdxaeroman** [comment]
WE DID IT!!!
